### ISSUE TITLE
autoreplace error

### ISSUE THREAD

**Issue by ToeKneeFan** [letsencrypt/openzfs-nvme-databases#14]
> We want to automatically activate hot spare drives if another drive fails: `autoreplace=on`.

This is a common misconception and widely misdocumented online in blogs and what not. In the [documentation ](https://openzfs.github.io/openzfs-docs/man/7/zpoolprops.7.html) for OpenZFS, they state that `autoreplace`

> Controls automatic device replacement. If set to off, device replacement must be initiated by the administrator by using the zpool replace command. If set to on, any new device, found in the same physical location as a device that previously belonged to the pool, is automatically formatted and replaced. The default behavior is off. This property can also be referred to by its shortened column name, [replace](https://openzfs.github.io/openzfs-docs/man/7/zpoolprops.7.html#replace). Autoreplace can also be used with virtual disks (like device mapper) provided that you use the /dev/disk/by-vdev paths setup by vdev_id.conf. See the [vdev_id(8)](https://openzfs.github.io/openzfs-docs/man/8/vdev_id.8.html) manual page for more details. Autoreplace and autoonline require the ZFS Event Daemon be configured and running. See the [zed(8)](https://openzfs.github.io/openzfs-docs/man/8/zed.8.html) manual page for more details.

That is, it controls behavior of _cold spares_, not hot spares. If a hard drive fails, and you replace it with a new hard drive in the same port, it will automatically assume that new drive should replace the older one.

**Comment by jprenken** [comment]
Many thanks for pointing this out!
