### ISSUE TITLE
Latency reports & benchmarks would be awesome!

### ISSUE THREAD

**Issue by monik3r** [letsencrypt/openzfs-nvme-databases#3]
Thanks for sharing this! It would be pretty neat to see benchmarks including throughput and lateness for requests (50%, 99%, 99.9%, etc) with stock openzfs & with the tuned settings here.

**Comment by jprenken** [comment]
Thanks! I agree, that would be pretty neat. Unfortunately, we don't have spare hardware available to run such a comparison.
