### ISSUE TITLE
How much memory to be allocated to ZFS ARC

### ISSUE THREAD

**Issue by samuelxhu** [letsencrypt/openzfs-nvme-databases#4]
I noticed that the system has a total of 2TB DDR4 memory, and i wonder that, what is the optimal allocation of memory between ARC memory and linux page cache for MySQL?

Does a kernel version play a role in performance? Which kernel version?

**Comment by jprenken** [comment]
We currently set `innodb_buffer_pool_size` to 80% of system memory, and leave most other allocations at their defaults. I wouldn't be confident making that a general recommendation, though: we haven't tested many different variations of these settings, and I imagine the results could be very different depending on the table structure. (e.g. We currently have some tables with extraordinarily large indexes; most people won't, and we're working to change that ourselves.)

I'm sure the kernel version does play a role, but that's another thing we haven't tried varying; and we don't disclose our exact internal OS usage, for security reasons.
