### ISSUE TITLE
Why not mdraid

### ISSUE THREAD

**Issue by edo1** [letsencrypt/openzfs-nvme-databases#6]
Thanks for sharing, this information is VERY interesting.

Could you please explain why you preferred OpenZFS to mdraid? Have you made a performance comparison?

**Comment by jprenken** [comment]
Thanks! No, we didn't do a head-to-head comparison with mdraid: we were pretty sure we wanted to start with ZFS' broader feature set, especially snapshotting and tiered caching. We haven't had a chance to experiment with caching yet, but have had much better luck with the performance and flexibility of ZFS' snapshots vs. LVM's.
